# Generated by Django 5.2.5 on 2025-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='articles')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=50)),
                ('Product_price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
