# Generated by Django 5.2.5 on 2025-09-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Product_price',
            new_name='price',
        ),
    ]
